### ISSUE TITLE
ECR: failed to request manifest head ...: request failed: unauthorized [http 403]

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-docker-build#121]
### What happened?

I'm seeing this error when attempting to refresh a stack with tags pushed to a private ECR.

Seems credentials aren't getting hooked up correctly.

### Example

n/a

### Output of `pulumi about`

v0.0.3.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by komalali** [comment]
@blampe is there any workaround/suggested fix for this?

**Comment by blampe** [comment]
Refresh uses credentials as they existed in state at the time of the update, so if those credentials have expired the refresh will fail. We can probably change the priority of lookups to prefer the environment over state, but workaround for now is to try updating the resource first.

**Comment by komalali** [comment]
Running into this issue in our staging stack now. It's been extremely painful to work around and even running an update doesn't really fix it if something else fails first and basically makes refreshes impossible so if you end up in a bad state you're kinda limited to state surgery as your only way out. Really hoping this gets prioritized!

**Comment by blampe** [comment]
This is essentially an instance of https://github.com/pulumi/pulumi/issues/4981.

I'm going to look into making read warn on 403s instead of failing.
