### ISSUE TITLE
I trying to publish image to ECR

### ISSUE THREAD

**Issue by tsibelman** [pulumi/pulumi-docker-build#241]
### What happened?

I copypasted example TS code from documentation https://www.pulumi.com/registry/packages/docker-build/api-docs/image/#push-to-aws-ecr-with-caching during deployment I get following error

14 pushing layers 0.1s done
#14 ERROR: failed to push agency-portal-846e1cad79b34ab8578e04b85f96de6a0d30af8a-1272: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Alibrary%2Fagency-portal-846e1cad79b34ab8578e04b85f96de6a0d30af8a-1272%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized
 
I don't understand why provider is trying to access docker for auth at this point and how I can solve this issue.

### Example

  const ecrRepository = new aws.ecr.Repository("ecr-repository", {});
  const authToken = aws.ecr.getAuthorizationTokenOutput({
    registryId: ecrRepository.registryId,
  });
  const myImage = new docker_build.Image("agency-portal", {
    tags: [`agency-portal-${configuration.tagbase}`],
    context: {
      location: "../..",
    },
    cacheFrom: [
      {
        registry: {
          ref: pulumi.interpolate`${ecrRepository.repositoryUrl}:cache`,
        },
      },
    ],

    cacheTo: [
      {
        registry: {
          imageManifest: true,
          ociMediaTypes: true,
          ref: pulumi.interpolate`${ecrRepository.repositoryUrl}:cache`,
        },
      },
    ],
    platforms: [docker_build.Platform.Linux_amd64],
    // Push the final result to ECR.
    push: true,

    // Provide our ECR credentials.
    registries: [
      {
        address: ecrRepository.repositoryUrl,

        password: authToken.apply((authToken) => authToken.password),
        username: authToken.apply((authToken) => authToken.userName),
      },
    ],
  });

### Output of `pulumi about`

It fails in CI/CD her output of relevant github action

Run pulumi/actions@v5
  with:
    command: up
    stack-name: novella/infra/core
    work-dir: shared/shr-cloud-infra
    upsert: true
    comment-on-pr: true
    comment-on-summary: true
    config-map: {"tagbase": {"value": "846e1cad79b34ab8578e04b85f96de6a0d30af8a-1[2](https://github.com/bynovella/novella/actions/runs/10639519543/job/29497625653?pr=478#step:14:2)72", "secret": false}, "smtpServerUrl": {"value": "***", "secret": true}, "baselimeKey": {"value": "***", "secret": true}, "googleMapsApiKey": {"value": "***", "secret": true}, "googleMapsApiKeyServer": {"value": "***", "secret": true}, "clerkSecretKey": {"value": "***", "secret": true}, "antropicSecretKey": {"value": "***", "secret": true}, "zendeskApiToken": {"value": "***", "secret": true}, "backofficeSecret": {"value": "***", "secret": true}, "clerkPublishableKey": {"value": "pk_test_cmFyZS10ZXJtaXRlLTE1LmNsZXJrLmFjY291bnRzLmRldiQ", "secret": true}}
    github-token: ***
    expect-no-changes: false
    diff: false
    target-dependents: false
    refresh: false
    remove: false
    edit-pr-comment: true
    color: auto
    exclude-protected: false
    suppress-outputs: false
    suppress-progress: false
    always-include-summary: false
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    PULUMI_ACCESS_TOKEN: ***
Configured range: 
/usr/local/bin/pulumi version
v[3](https://github.com/bynovella/novella/actions/runs/10639519543/job/29497625653?pr=478#step:14:3).130.0
Pulumi version 3.130.0 is already installed on this machine. Skipping download
Logging into the Pulumi Cloud backend.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@tsibelman your image's tag needs to include the repo URL. It looks like you're tagging it as 
```
tags: [agency-portal-${configuration.tagbase}],
```
which doesn't include a URL, so it's assumed to be a dockerhub tag.

From [the docs](https://www.pulumi.com/registry/packages/docker-build/api-docs/image/):

> If exporting to a registry, the name should include the fully qualified registry address (e.g. docker.io/pulumi/pulumi:latest).
