### ISSUE TITLE
Field 'registries' on 'internal.Config' must be a '[]internal.Registry'; got 'string' instead

### ISSUE THREAD

**Issue by wSedlacek** [pulumi/pulumi-docker-build#262]
### What happened?

When trying to use `registries` on the `dockerBuild.Provider()` the following error occurs
```
Field 'registries' on 'internal.Config' must be a '[]internal.Registry'; got 'string' instead
```

### Example

```
  const provider = new dockerBuild.Provider(containerRegistry, {
    registries: [{ address: `${protocol}//${registry.host}`, username, password }],
  });
```

### Output of `pulumi about`

CLI          
Version      3.133.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  3.133.0-dev.0

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/coder/.local/state/fnm_multishells/4830_1726756733695/bin/node' version='v20.14.0'

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:development-1bba0bae::rocket::pulumi:pulumi:Stack::rocket-development-1bba0bae
pulumi:providers:pulumi        urn:pulumi:development-1bba0bae::rocket::pulumi:providers:pulumi::default
pulumi:providers:aws           urn:pulumi:development-1bba0bae::rocket::pulumi:providers:aws::default_6_52_0
pulumi:pulumi:StackReference   urn:pulumi:development-1bba0bae::rocket::pulumi:pulumi:StackReference::development-1bba0bae
pulumi:providers:kubernetes    urn:pulumi:development-1bba0bae::rocket::pulumi:providers:kubernetes::coder
kubernetes:helm.sh/v3:Release  urn:pulumi:development-1bba0bae::rocket::kubernetes:helm.sh/v3:Release::secrets
kubernetes:helm.sh/v3:Release  urn:pulumi:development-1bba0bae::rocket::kubernetes:helm.sh/v3:Release::security
kubernetes:helm.sh/v3:Release  urn:pulumi:development-1bba0bae::rocket::kubernetes:helm.sh/v3:Release::pg-config
kubernetes:helm.sh/v3:Release  urn:pulumi:development-1bba0bae::rocket::kubernetes:helm.sh/v3:Release::roles
kubernetes:helm.sh/v3:Release  urn:pulumi:development-1bba0bae::rocket::kubernetes:helm.sh/v3:Release::pg-cluster
pulumi:providers:command       urn:pulumi:development-1bba0bae::rocket::pulumi:providers:command::default_1_0_1
pulumi:providers:docker-build  urn:pulumi:development-1bba0bae::rocket::pulumi:providers:docker-build::default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@wSedlacek what version of the docker-build provider are you using?

**Comment by wSedlacek** [comment]
@blampe the plugin is also 0.0.6.
The TypeScript interface is also [v0.0.6](https://www.npmjs.com/package/@pulumi/docker-build/v/0.0.6) 

```
pulumi plugin ls
NAME          KIND      VERSION  SIZE    INSTALLED   LAST USED
command       resource  1.0.1    35 MB   2 days ago  2 days ago
docker        resource  4.5.5    49 MB   2 days ago  2 days ago
docker-build  resource  0.0.6    118 MB  2 days ago  2 days ago
kubernetes    resource  4.18.1   214 MB  2 days ago  2 days ago

TOTAL plugin cache size: 416 MB
```
