### ISSUE TITLE
plugin for docker build gives 403

### ISSUE THREAD

**Issue by suhabe-lamini** [pulumi/pulumi-docker-build#93]
### What happened?

Using the go sdk with the docker-build plugin, when I do a pulumi up, I get a 403 forbidden error as shown below.

### Example

~/migration/control/cli> pulumi up                                                                                                                              06/04/2024 05:31:11 PM
Previewing update (dev):
     Type                              Name                            Plan       Info
     pulumi:pulumi:Stack               llama-dev                                 
 +   ├─ kubernetes:core/v1:Namespace   llama-local                    create     
     └─ pulumi:providers:docker-build  default_0_1_0_alpha_1717073454             1 error

Diagnostics:
  pulumi:providers:docker-build (default_0_1_0_alpha_1717073454):
    error: Could not automatically download and install resource plugin 'pulumi-resource-docker-build' at version v0.1.0-alpha.1717073454, install the plugin using `pulumi plugin install resource docker-build v0.1.0-alpha.1717073454`: error downloading provider docker-build to file: failed to download plugin: docker-build-0.1.0-alpha.1717073454: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-docker-build-v0.1.0-alpha.1717073454-darwin-arm64.tar.gz

### Output of `pulumi about`

~/migration/control/cli> pulumi about                                                                                                                           06/04/2024 05:32:40 PM
CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  docker-build  0.1.0-alpha.1717073454
language  go            unknown
resource  kubernetes    4.12.0

Host     
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.22.2 darwin/arm64'

Current Stack: organization/llama/dev

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:dev::llama::pulumi:pulumi:Stack::-dev
pulumi:providers:kubernetes    urn:pulumi:dev::::pulumi:providers:kubernetes::default_4_12_0
kubernetes:core/v1:Namespace   urn:pulumi:dev::::kubernetes:core/v1:Namespace::-dev
kubernetes:apps/v1:Deployment  urn:pulumi:dev::::kubernetes:apps/v1:Deployment::api

Found no pending operations associated with dev

Backend        
Name           Llamas-Laptop.attlocal.net
URL            file://~
User           llama
Organizations  
Token type     personal

Dependencies:
NAME                                             VERSION
github.com/llama/llama-platform/control/infra  v0.0.0-00010101000000-000000000000
github.com/pulumi/pulumi/sdk/v3                  v3.118.0

Pulumi locates its logs in /var/folders/3h/fddrvtpn44g87zc2584mgmk40000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
I think the latest docker-build release predates our work to fix SDK versions in go and the engine is defaulting to pick up the version from the main branch (which is not released). We may be able to fix this just by making a patch release of this provider.

**Comment by mjeffryes** [comment]
I kicked off a new release: https://github.com/pulumi/pulumi-docker-build/actions/runs/9491112518

**Comment by danielrbradley** [comment]
I've created the tag manually: [`sdk/go/dockerbuild/v0.0.3`](https://github.com/pulumi/pulumi-docker-build/releases/tag/sdk%2Fgo%2Fdockerbuild%2Fv0.0.3) and confirmed it can be pulled manually:

```
go get github.com/pulumi/pulumi-docker-build/sdk/go/dockerbuild@v0.0.3                   
go: downloading github.com/pulumi/pulumi-docker-build/sdk/go/dockerbuild v0.0.3
go: added dario.cat/mergo v1.0.0
go: added github.com/Microsoft/go-winio v0.6.1
go: added github.com/ProtonMail/go-crypto v1.0.0
go: added github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: added github.com/agext/levenshtein v1.2.3
go: added github.com/apparentlymart/go-textseg/v15 v15.0.0
go: added github.com/atotto/clipboard v0.1.4
go: added github.com/aymanbagabas/go-osc52/v2 v2.0.1
go: added github.com/blang/semver v3.5.1+incompatible
go: added github.com/charmbracelet/bubbles v0.16.1
go: added github.com/charmbracelet/bubbletea v0.24.2
go: added github.com/charmbracelet/lipgloss v0.7.1
go: added github.com/cheggaaa/pb v1.0.29
go: added github.com/cloudflare/circl v1.3.7
go: added github.com/containerd/console v1.0.4
go: added github.com/cyphar/filepath-securejoin v0.2.4
go: added github.com/djherbis/times v1.5.0
go: added github.com/emirpasic/gods v1.18.1
go: added github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376
go: added github.com/go-git/go-billy/v5 v5.5.0
go: added github.com/go-git/go-git/v5 v5.12.0
go: added github.com/gogo/protobuf v1.3.2
go: added github.com/golang/glog v1.2.0
go: added github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: added github.com/google/uuid v1.6.0
go: added github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
go: added github.com/hashicorp/errwrap v1.1.0
go: added github.com/hashicorp/go-multierror v1.1.1
go: added github.com/hashicorp/hcl/v2 v2.19.1
go: added github.com/inconshreveable/mousetrap v1.1.0
go: added github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: added github.com/kevinburke/ssh_config v1.2.0
go: added github.com/lucasb-eyer/go-colorful v1.2.0
go: added github.com/mattn/go-isatty v0.0.20
go: added github.com/mattn/go-localereader v0.0.1
go: added github.com/mattn/go-runewidth v0.0.15
go: added github.com/mitchellh/go-ps v1.0.0
go: added github.com/mitchellh/go-wordwrap v1.0.1
go: added github.com/muesli/ansi v0.0.0-20230316100256-276c6243b2f6
go: added github.com/muesli/cancelreader v0.2.2
go: added github.com/muesli/reflow v0.3.0
go: added github.com/muesli/termenv v0.15.2
go: added github.com/opentracing/basictracer-go v1.1.0
go: added github.com/opentracing/opentracing-go v1.2.0
go: added github.com/pgavlin/fx v0.1.6
go: added github.com/pjbgf/sha1cd v0.3.0
go: added github.com/pkg/errors v0.9.1
go: added github.com/pkg/term v1.1.0
go: added github.com/pulumi/appdash v0.0.0-20231130102222-75f619a67231
go: added github.com/pulumi/esc v0.6.2
go: added github.com/pulumi/pulumi-docker-build/sdk/go/dockerbuild v0.0.3
go: added github.com/pulumi/pulumi/sdk/v3 v3.117.1-0.20240525040238-ee831fc5b644
go: added github.com/rivo/uniseg v0.4.4
go: added github.com/rogpeppe/go-internal v1.12.0
go: added github.com/sabhiram/go-gitignore v0.0.0-20210923224102-525f6e181f06
go: added github.com/santhosh-tekuri/jsonschema/v5 v5.3.1
go: added github.com/sergi/go-diff v1.3.2-0.20230802210424-5b0b94c5c0d3
go: added github.com/skeema/knownhosts v1.2.2
go: added github.com/spf13/cobra v1.8.0
go: added github.com/spf13/pflag v1.0.5
go: added github.com/texttheater/golang-levenshtein v1.0.1
go: added github.com/tweekmonster/luser v0.0.0-20161003172636-3fa38070dbd7
go: added github.com/uber/jaeger-client-go v2.30.0+incompatible
go: added github.com/uber/jaeger-lib v2.4.1+incompatible
go: added github.com/xanzy/ssh-agent v0.3.3
go: added github.com/zclconf/go-cty v1.14.1
go: added go.uber.org/atomic v1.10.0
go: added golang.org/x/crypto v0.23.0
go: added golang.org/x/exp v0.0.0-20240112132812-db7319d0e0e3
go: added golang.org/x/mod v0.16.0
go: added golang.org/x/net v0.25.0
go: added golang.org/x/sync v0.6.0
go: added golang.org/x/sys v0.20.0
go: added golang.org/x/term v0.20.0
go: added golang.org/x/text v0.15.0
go: added golang.org/x/tools v0.19.0
go: added google.golang.org/genproto/googleapis/rpc v0.0.0-20240311173647-c811ad7063a7
go: added google.golang.org/grpc v1.63.2
go: added google.golang.org/protobuf v1.33.0
go: added gopkg.in/warnings.v0 v0.1.2
go: added gopkg.in/yaml.v3 v3.0.1
go: added lukechampine.com/frand v1.4.2
```
